### ISSUE TITLE
patterdale does not specify any memory arguments to JVM

### ISSUE THREAD

**Issue by baggiobaggio** [tjheslin1/Patterdale#16]
Should add Xms, Xmx and  XX:MaxMetaspaceSize

**Comment by tjheslin1** [comment]
Good point! I will add sensible defaults and if necessary I will make them configurable in the future.

**Comment by tjheslin1** [comment]
Resolved in [release 0.18.0](https://github.com/tjheslin1/Patterdale/releases/tag/0.18.0)

**Comment by tjheslin1** [comment]
@baggiobaggio I've address an issue with memory arguments formatting in the `Dockerfile` in [version 1.0.0](https://github.com/tjheslin1/Patterdale/releases/tag/1.0.0).
