### ISSUE TITLE
Patterdale fails to start if the database is down

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Patterdale#17]
This is a problem when using patterdale to e.g. monitor if the database is up.

Not sure what we can do about this...

**Comment by tjheslin1** [comment]
Currently it'll attempt the configurable number of times to connect to the databases it knows about.

Another approach would be to use that configuration option to instead retry failed connections periodically, leaving the app running and ready as soon as the database is available.

I'll look at this this evening 👍

**Comment by tjheslin1** [comment]
So one option would be to start the web server up and then attempt database connections. Currently it retries, according to configuration, until all databases have been succesfully connected to. In other words, when all `HikariDataSource`s have been created. Only then does the web server start up.

This was designed under the assumption that all databases to be monitored are already running. The connection retries came out of waiting for a database to fully start up, the `sath89/oracle` database takes roughly 5 mins.

Can you expand on a scenario where a database wouldn't be running already? Connection configuration would have to be assumed ahead of time.

**Comment by theangrydev** [comment]
Example scenario: performing a Patterdale release at a time that one of the databases it monitors is down for maintenance

**Comment by tjheslin1** [comment]
Makes sense. I'll keep the retry mechanism but not fail the web server.

**Comment by tjheslin1** [comment]
I can work on this soon, however if it's urgent feel free to contribute.
