### ISSUE TITLE
Race condition in DatabaseDownTest

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Patterdale#27]
The `DatabaseDownTest` is failing because of a race condition. There is a sleep where we are trying to wait for the h2 database to actually be down and for the patterdale cache to be cleared.

**Comment by tjheslin1** [comment]
Addressed in commit [ea34569](https://github.com/tjheslin1/Patterdale/commit/ea345690f172fff94e16df8740e56c1bb7ff4e7a)
