### ISSUE TITLE
Do not render metrics on probe errors

### ISSUE THREAD

**Issue by tommagowan** [tjheslin1/Patterdale#32]
When paterdale attempts to query a database probe and an error is returned, a default ProbeResult, with a value of -1 is returned. See code [here](https://github.com/tjheslin1/Patterdale/blob/05a2a2f96017335aaf0225cf9c8e0c596164c9a6/src/main/java/io/github/tjheslin1/patterdale/metrics/probe/ListOracleSQLProbe.java#L93) and [here](https://github.com/tjheslin1/Patterdale/blob/05a2a2f96017335aaf0225cf9c8e0c596164c9a6/src/main/java/io/github/tjheslin1/patterdale/metrics/probe/ExistsOracleSQLProbe.java#L85).

This leads to time series metrics being rendered like this if there are dynamic labels:

```database_tablespace_free{database="MyDB",tableSpaceName="%s"}```

This generates a new metric time series that is not relevant.

The fix should probably be not to render metrics for probes that have failed. However, database_up metric should be able to render on such an error.

**Comment by tjheslin1** [comment]
Agreed, in this case the error should be logged and no unformatted metrics, polluting the time-series, should be exposed.

**Comment by tjheslin1** [comment]
Addressed in commit: [527fbbb](https://github.com/tjheslin1/Patterdale/commit/527fbbb6a9d2938df4766d1a3a4518d05009262e). Will release alongisde #33 when that's completed.

**Comment by tjheslin1** [comment]
Addressed in release [1.2.4](https://github.com/tjheslin1/Patterdale/releases/tag/1.2.4)
