### ISSUE TITLE
Make the end to end tests work in the CI build

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Patterdale#4]

**Comment by tjheslin1** [comment]
This is in progress. I need to configure TravisCI to wait for the sath89/oracle-12c containers to full start, likely by grep'ing the container logs.

**Comment by tjheslin1** [comment]
This has been fixed.

**Comment by tjheslin1** [comment]
The integration can now be tested with `docker-compose.yml` as well as the test which runs in CI.
