### ISSUE TITLE
Metrics are missing HELP and TYPE

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Patterdale#8]
For example:

```
# HELP jvm_threads_current Current thread count of a JVM
# TYPE jvm_threads_current gauge
jvm_threads_current 18.0

# HELP jetty_responses Number of requests with response status
# TYPE jetty_responses gauge
jetty_responses{code="1xx",} 0.0
jetty_responses{code="2xx",} 135170.0
jetty_responses{code="3xx",} 0.0
jetty_responses{code="4xx",} 126.0
jetty_responses{code="5xx",} 2.0
```

I am having trouble getting prometheus to interpret the metrics, it seems to be scraping them but they are not available to query.

**Comment by theangrydev** [comment]
The issue with not scraping properly might be unrelated to this, it could be due to e.g. not escaping labels properly or something like that. Have not been able to investigate yet.

**Comment by tjheslin1** [comment]
I don't believe the HELP/TYPE comments are necessary. My guess would be the formatting itself. I'll investigate this with minikube.

I should start to test this with a real Prometheus scraping Patterdale, in minikube.

**Comment by tjheslin1** [comment]
Running `docker-compose.yml` confirms the app is compatible with Prometheus. I would recommend not having HELP and TYPE comments for the custom metrics as the comments would have to be provided alongside each metric in `patterdale.yml`.

Another argument is that providing custom SQL queries as metrics suggests an understanding of the metrics.

Does this sound fair?

**Comment by tjheslin1** [comment]
@theangrydev can this be closed?

**Comment by theangrydev** [comment]
Yes, this is not impacting us so no problem on our side.
