### ISSUE TITLE
Queries in slowest_queries end up truncated

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Patterdale#9]
Can't remember if this is intentional or not?

**Comment by theangrydev** [comment]
For example, detecting itself, it finds `sqlText="SELECT * FROM (SELECT s.elapsed_time / s.executions / 1000 AS AVG_ELAPSED_TI"` not the entire query for some reason.

**Comment by tjheslin1** [comment]
The example query I provide truncates the query to 80 chars:

`SUBSTR(s.sql_fulltext, 1, 80) AS SQL_TEXT`

See [configuration.md](https://github.com/tjheslin1/Patterdale/blob/4aff6776fd4e8cdd8767224c6c4de916cfd94111/docs/configuration.md) which has the full example (this matches `src/test/resources/patterdale.yml`.

**Comment by theangrydev** [comment]
Whoops, thanks missed that somehow
